# Generated by Django 5.2.8 on 2025-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название товара"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=7000,
                        null=True,
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Стоимость"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "рубль"), ("USD", "доллар")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество товара(-ов)"
                    ),
                ),
            ],
        ),
    ]
